### PR TITLE
Fix some typos and group link rendering

### LINKED ISSUE #279: ct-groups.md has links that are not shown
website/content/contribute/ct-groups.md has links to Community 1 and Community 2 but those are not rendered

### PR DESCRIPTION
**Pull request by whikloj**
Resolves #279 

Though I don't think you actually want those fake working groups in there, so I can remove them once you are happy.

### CODE REVIEW

**Comment by whikloj** [comment]
Just an FYI, in the CLAassistant verbiage it says
> You agree to license all of your rights in each of your Contributions, under the terms of the specific "Applicable License" designated on the home page of the repository into which it is submitted, for the benefit of both OASIS and all later parties who that Applicable License benefits.

The `website` repository does not seem to have a license designated.

**Comment by jamsden** [comment]
Contributions are to the https://github.com/oslc-op/oslc-specs repo, not the web site, and the readme covers [Licensing](https://github.com/oslc-op/oslc-admin/blob/master/LICENSE.md)

**Comment by whikloj** [comment]
Sorry perhaps I am misunderstanding
> You agree to license all of your rights in each of your Contributions, under the terms of the specific "Applicable License" designated on the **home page of the repository into which it is submitted** ...

I am submitting my contribution here (`oslc-op/website`), not into the `oslc-op/oslc-specs` or `oslc-op/oslc-admin` repository. I was just noting that I looked for and expected to see a `LICENSE` file in this repo. If this contribution is in the wrong location, I apologize.

**Comment by Jad-elkhouy** [comment]
@jamsden!

It makes things clearer for everyone if there is a clear licensing information on each repo. We can refer of course to a single licensing text to avoid duplication.

Can we simply add to the readme on this repo (https://github.com/oslc-op/website) the same 1 line as we have under https://github.com/oslc-op/oslc-specs#licensing. That in turn refers to a since License file.

**Comment by jadelkhoury** [comment]
Something like this?
https://github.com/oslc-op/website/pull/312

**Comment by berezovskyi** [comment]
Thanks @whikloj, thanks for fixing the typos and spotting the placeholder working group links.

@Jad-el-khoury @jamsden do you want to create a page for the OSLC OP Product group? Otherwise, I think it would be great if @whikloj could remove the placeholders.

**Comment by jadelkhoury** [comment]
Not sure what your suggestion is @berezovskyi . 
We already have a [Contribute](https://www.open-services.net/contribute/) page. Maybe we can simply lift the OSLC OP box from the bottom of that page to the top, making it more visible?

**Comment by jadelkhoury** [comment]
Otherwise, I don't see problems with the changes suggested by @whikloj .

**Comment by whikloj** [comment]
Hey @jadelkhoury, I could be wrong but I think the file `content\contribute\ct-groups.md` actually generates the page ([Contribute](https://www.open-services.net/contribute/)) you linked to. 

There were extra placeholder variables that were never used and I made a change to make the list of "working groups" into a list that would dynamically add a new box for each entry.

I'll just remove the two old placeholders ("Community 1" and "Community 2") and if there is a need for a new group box someone can just add a new entry to the list.

**Review by berezovskyi — APPROVED** [review]

**Comment by berezovskyi** [comment]
@whikloj thanks a lot for the contribution and the PR adjustments!

@jadelkhoury I checked the rendering locally, it all looks good. If you want to move blocks around on that page, please open a separate PR.

**Pull request merged**
