### PR TITLE
Updated Core 3.0 links to published PDC04

### PR DESCRIPTION
**Pull request by jamsden**

### CODE REVIEW

**Comment by berezovskyi** [comment]
Did you have a chance to update the PR?

**Comment by jamsden** [comment]
I would recommend against that the csprd is no longer relevant and I think we should avoid adding things that could lead to confusion.

**Comment by berezovskyi** [comment]
Yes, it is no longer relevant. But those were published documents and I don't want to erase any references. Just to avoid the situation we are having now with provenance repeating in a couple years.

**Comment by berezovskyi** [comment]
I took a liberty of editing your PR a bit before merging. If you think obsolete links are distracting, we can move them elsewhere but I want to keep track of them.

**Pull request merged**
