### PR TITLE
updates sponsorship language revisions requested by OASIS legal counsel

### PR DESCRIPTION
**Pull request by jorydotcom**
Per our thread on the mailing list, here is a PR with minor language tweaks in the sponsors and PGB sections. I also made some spelling corrections. Note that I had to modify a theme layout to get the links to render properly.

### CODE REVIEW

**Comment by berezovskyi** [comment]
Excellent! Thanks Jory for submitting a PR and fixing a few of our typos along the way 🙈 Great to clarify that PGB members must sign the CLA. I believe everyone on the PGB has it on file and it is a common understanding that you need one to join the PGB.

@jamsden please review too.

**Comment by berezovskyi** [comment]
Thanks all! I will publish the changes soon

**Comment by jorydotcom** [comment]
@berezovskyi, Chet & I were wondering when you would be able to deploy these changes to the live site? thanks!

**Comment by berezovskyi** [comment]
@jorydotcom the changes should be live now.

**Pull request merged**
