### PR TITLE
Add Config PSD to the list of publications

### PR DESCRIPTION
**Pull request by berezovskyi**

### CODE REVIEW

**Review by gabrielfdac — APPROVED** [review]

**Comment by berezovskyi** [comment]
That was too early, the link is still 404. But OK, OASIS should fix it soon :)

**Comment by berezovskyi** [comment]
I should have marked the PR donotmerge, but thank you for checking up on active PRs!

**Comment by gabrielfdac** [comment]
Ah, apologies. Should've asked if it was ready

**Comment by berezovskyi** [comment]
For the record: the link https://docs.oasis-open-projects.org/oslc-op/config/v1.0/psd01/oslc-config-mgt.html is now up on OASIS docarc

**Pull request merged**
